/*
  THE COIL — main.js
  Small, dependency-free interactive enhancements.
  The site is fully usable with JavaScript disabled:
  - navigation links work without the toggle (mobile falls back to a normal
    in-flow list if .open is never applied)
  - article content is not generated by JS
  - the contact form degrades to a plain (client-only) form
*/

(function () {
  'use strict';

  /* ---------- Mobile navigation toggle ---------- */
  var navToggle = document.querySelector('.nav-toggle');
  var primaryNav = document.querySelector('.primary-nav');

  if (navToggle && primaryNav) {
    navToggle.addEventListener('click', function () {
      var isOpen = primaryNav.classList.toggle('open');
      navToggle.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
    });

    // Close menu when a nav link is clicked (mobile)
    primaryNav.querySelectorAll('a').forEach(function (link) {
      link.addEventListener('click', function () {
        primaryNav.classList.remove('open');
        navToggle.setAttribute('aria-expanded', 'false');
      });
    });

    // Close on Escape
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && primaryNav.classList.contains('open')) {
        primaryNav.classList.remove('open');
        navToggle.setAttribute('aria-expanded', 'false');
        navToggle.focus();
      }
    });
  }

  /* ---------- Current year in footer ---------- */
  var yearEl = document.getElementById('current-year');
  if (yearEl) {
    yearEl.textContent = new Date().getFullYear();
  }

  /* ---------- Article reading progress indicator ---------- */
  var progressBar = document.querySelector('.reading-progress');
  var articleBody = document.querySelector('.article-body');

  if (progressBar && articleBody) {
    var updateProgress = function () {
      var rect = articleBody.getBoundingClientRect();
      var articleTop = rect.top + window.scrollY;
      var articleHeight = articleBody.offsetHeight;
      var viewportHeight = window.innerHeight;
      var scrolled = window.scrollY - articleTop + viewportHeight * 0.5;
      var percent = Math.min(100, Math.max(0, (scrolled / articleHeight) * 100));
      progressBar.style.width = percent + '%';
    };
    window.addEventListener('scroll', updateProgress, { passive: true });
    window.addEventListener('resize', updateProgress);
    updateProgress();
  }

  /* ---------- Web Share API (falls back to copy-link) ---------- */
  var shareButtons = document.querySelectorAll('[data-share]');
  shareButtons.forEach(function (btn) {
    btn.addEventListener('click', function () {
      var shareData = {
        title: document.title,
        text: 'Read this on The Coil (mock/parody site):',
        url: window.location.href
      };
      if (navigator.share) {
        navigator.share(shareData).catch(function () {
          /* user cancelled share — no action needed */
        });
      } else if (navigator.clipboard) {
        navigator.clipboard.writeText(window.location.href).then(function () {
          var original = btn.textContent;
          btn.textContent = 'Link copied!';
          setTimeout(function () { btn.textContent = original; }, 1800);
        });
      }
    });
  });

  /* ---------- Demo contact form (no backend — GitHub Pages static site) ---------- */
  var contactForm = document.getElementById('contact-form');
  var contactSuccess = document.getElementById('form-success');

  if (contactForm && contactSuccess) {
    contactForm.addEventListener('submit', function (e) {
      e.preventDefault();
      // This is a static demonstration form. No data is sent anywhere.
      contactSuccess.classList.add('visible');
      contactForm.reset();
      contactSuccess.focus();
    });
  }
})();
